#! /usr/bin/env python3
# Blashyrkh.maniac.coding
# BTC:1Maniaccv5vSQVuwrmRtfazhf2WsUJ1KyD DOGE:DManiac9Gk31A4vLw9fLN9jVDFAQZc2zPj

import my
import binascii

config=my.Config()
db=my.DatabaseConnectionFactory.connect(config["database"])
#hmac=config["depo"]["hmac"]

h=my.cgijsonrpc.Handler()

h.setOutgoingHMAC(keyid=None, key=None)

h.addMethod("get-address", my.rpc.GetAddress(db=db, config=config))
h.addMethod("get-tx-status", my.rpc.GetTxStatus(db=db))
h.addMethod("send", my.rpc.Send(db=db, config=config))

# TODO: estimate-fee
# TODO: ext


h.run()
