#! /usr/bin/env python3
# Blashyrkh.maniac.coding
# BTC:1Maniaccv5vSQVuwrmRtfazhf2WsUJ1KyD DOGE:DManiac9Gk31A4vLw9fLN9jVDFAQZc2zPj

import my

config=my.Config()
db=my.DatabaseConnectionFactory.connect(config["database"])

for r in db.getPendingDepositAddressRequests():
    my.generators.generateAddress(db=db, config=config, userid=r.userid, coin=r.coin)

