#! /usr/bin/env python3
# Blashyrkh.maniac.coding
# BTC:1Maniaccv5vSQVuwrmRtfazhf2WsUJ1KyD DOGE:DManiac9Gk31A4vLw9fLN9jVDFAQZc2zPj

import my

config=my.Config()
db=my.DatabaseConnectionFactory.connect(config["database"])

for r in db.getPendingDepositAddressRequests():
    my.generators.generateAddress(db=db, config=config, userid=r.userid, coin=r.coin)

ethqueue=my.ethqueue.Queue(db=db, config=config)
for t in db.getPendingTransactions():
    ethqueue.processTransaction(t.uuid)

my.scanners.scanDeposits(db=db, config=config)
